using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace SimpleCrm.SqlDbServices
{
    public class SqlCustomerData : ICustomerData
    {
        private readonly SimpleCrmDbContext dbContext;

        public SqlCustomerData(SimpleCrmDbContext dbContext)
        {
            this.dbContext = dbContext;
        }
        public Customer Get(int id)
        {
            return dbContext.Customers.FirstOrDefault((item) => item.Id == id);
        }

        public IEnumerable<Customer> GetAll()
        {
            return dbContext.Customers;
        }

        public void Save(Customer customer)
        {
/* not needed, generated by the database            customer.Id = dbContext.Customers.Max(a => a.Id) + 1; */
            dbContext.Add(customer);
            dbContext.SaveChanges();
        }
    }
}
